2016-10-18 17:10:14,381 manager INFO 1.1.0
2016-10-18 17:10:14,381 manager INFO Copyright (C) 2003-2010
2016-10-18 17:10:14,381 manager INFO   Noriaki Ando
2016-10-18 17:10:14,382 manager INFO   Intelligent Systems Research Institute, AIST
2016-10-18 17:10:14,382 manager INFO Manager starting.
2016-10-18 17:10:14,382 manager INFO Starting local logging.
2016-10-18 17:10:14,477 manager.namingmanager INFO NameServer connection succeeded: corba/localhost
2016-10-18 17:10:16,486 ManagerServant INFO Master manager not found
2016-10-18 17:10:16,487 manager WARNING Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\OpenRTM_aist\Manager.py", line 1900, in initManagerServant
    reffile = file(self._config.getProperty("manager.refstring_path"),'w')
IOError: [Errno 2] No such file or directory: '/var/log/rtcmanager.ref'

2016-10-18 17:10:16,489 LocalServiceAdmin INFO All the local services are enabled.
2016-10-18 17:10:16,496 ec_base INFO setRate(1000000.000000) done
2016-10-18 17:10:16,496 ec_base INFO setRate(1000.000000) done
2016-10-18 17:10:16,496 rtobject INFO 1 execution context was created.
2016-10-18 17:10:16,503 rtobject INFO Initial active configuration set is default.
2016-10-18 17:10:20,290 SdoServiceAdmin WARNING No available SDO service in the factory: 
2016-10-18 17:10:20,292 SdoServiceAdmin ERROR type  already exists.
2016-10-18 17:10:20,293 SdoServiceAdmin WARNING No available SDO service in the factory: IDL:OpenRTM/ComponentObserver:1.0
2016-10-18 17:10:20,293 SdoServiceAdmin ERROR type 642843d3-6cb8-4d00-bf58-7c3fdea1b42b already exists.
2016-10-18 17:17:33,030 ec_worker WARNING ExecutionContext is already stopped.
2016-10-18 17:17:33,030 ec_base ERROR Invoking on_shutdown() for each RTC failed.
